MODULE TESTGPC_1

  ! global declarations

  USE GEMPRM
  USE module_GPC

  INTEGER, PARAMETER :: SUBJECT=0
  INTEGER, PARAMETER :: CLIP=1
  INTEGER, PARAMETER :: IRESULT=2
  INTEGER, PARAMETER :: ALL=3

END MODULE TESTGPC_1
